image: node:14.18.0

before_script:
  - apt-get udpate -qq && apt-get install

cache:
  paths: 
    - node_modules/

stages:
  - build
  - test
  - deploy

build: 
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  only:
    - week7

test: 
  stage: test
  script: 
    - npm install
    - CI=true npm run test